print("Bienvenido al juego del ahorcado!")
print("Vamos a empezar!")   
print("Estoy pensando en una palabra de 5 letras")
print("Tienes 5 intentos para adivinarla")
print("¡Buena suerte!")
print("La palabra es:")
print("_ _ _ _ _")
print("Ingresa una letra:")
